<style type="text/css">
    ol { list-style-type: upper-alpha; }
</style>

<center> <img src=https://i.imgur.com/0TSSaqL.png width="550"> </center>

<center> <h3> Module 3: Programación en Python </h3> </center>
<center> <h4> Sesiones síncronas - 20230104 - 2/2</h4> </center>

## Numpy

### **Ejercicio 1**

Escribir un programa que cree:
1. Un array vacío
2. Un array de ceros
3. Un array de valores 1 a 5
4. Una matriz diagonal de valores 1 a 5

Y nos muestre por cada uno de ellos sus dimensiones y el número de elementos que contiene.

In [ ]:
# Ejercicio 1

import numpy as np

def print_arr(arr):
  print("Array:\n", arr)
  print("Dimensiones:", arr.ndim)
  print("Size:", arr.size)

print_arr(np.empty([5]))
print_arr(np.zeros([10]))
print_arr(np.arange(1,6))
print_arr(np.diagflat(np.arange(1,6)))


Array:
 [4.9e-324 9.9e-324 1.5e-323 2.0e-323 2.5e-323]
Dimensiones: 1
Size: 5
Array:
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Dimensiones: 1
Size: 10
Array:
 [1 2 3 4 5]
Dimensiones: 1
Size: 5
Array:
 [[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]
Dimensiones: 2
Size: 25


### **Ejercicio 2**
Escribir un programa que, dados dos arrays, lleve a cabo:
1. La unión
2. La intersección
3. La suma
4. La multiplicación por un valor constante


In [ ]:
# Ejercicio 2

import numpy as np

x = np.array([7, 5, 89, 22])
y = np.array([22, 7, 78, 34])

print("x=", x)
print("y=", y)
print("Unión=", np.union1d(x, y))
print("Intersección=", np.intersect1d(x, y))
print("Suma=", x + y)
print("Multiplicación * 5=", x * 5)


x= [ 7  5 89 22]
y= [22  7 78 34]
Unión= [ 5  7 22 34 78 89]
Intersección= [ 7 22]
Suma= [ 29  12 167  56]
Multiplicación * 5= [ 35  25 445 110]


## Ejercicio 3
Escribir un programa que dados dos arrays los compare.

In [ ]:
# Ejercicio 3

import numpy as np

x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
  
print("x:", x)
print("y:", y)
print("x == y:", np.array_equal(x, y))
print("x > y:", np.greater(x, y))
print("x >= y:", np.greater_equal(x, y))
print("x < y:", np.less(x, y))
print("x <= y:", np.less_equal(x, y))


x: [1 2 3]
y: [3 2 1]
x == y: False
x > y: [False False  True]
x >= y: [False  True  True]
x < y: [ True False False]
x <= y: [ True  True False]


### **Ejercicio 4**
Escribir un programa que cree un array de temperaturas en grados fahrenheit y transforme todos sus elementos a grados centígrados. Recordad que la fórmula utilizada para la conversión es:
\begin{equation}
C = \frac{5}{{9}} \left(F - 32 \right)
\end{equation}

In [ ]:
# Ejercicio 4

def farenheit_to_celsius(f_value):
  return round((5 * (f_value - 32)) / 9, 2)

in_farenheit = [86, 39.2, 57.2, 76.1, 100, 80.6]
to_celsius = np.vectorize(farenheit_to_celsius)
in_celsius = to_celsius(in_farenheit)
print("Farenheit:", in_farenheit)
print("Celsius:", in_celsius)


Farenheit: [86, 39.2, 57.2, 76.1, 100, 80.6]
Celsius: [30.    4.   14.   24.5  37.78 27.  ]


### **Ejercicio 5**
Escribir un programa que cree una matriz de dimensión 3x5 y otra de dimensión 5x4, con valores aleatorios, y calcule su multiplicación.

In [ ]:
# Ejercicio 5

a = np.random.random((3,5))
b = np.random.random((5,4))

print("a:\n", a)
print("b:\n", b)
print("Producto punto:\n", np.dot(a, b))
print("Multiplicación:\n", np.matmul(a, b))

a:
 [[0.81315306 0.80689432 0.73023498 0.8473674  0.85750939]
 [0.07755377 0.00099882 0.30096113 0.94515882 0.00886732]
 [0.12420796 0.71438513 0.8039229  0.05328186 0.81603842]]
b:
 [[0.44572113 0.98103875 0.59955578 0.29118213]
 [0.77208506 0.56227812 0.85875867 0.40113493]
 [0.79693103 0.5298154  0.44174919 0.34635764]
 [0.68787782 0.26000885 0.49171805 0.3601268 ]
 [0.0146603  0.82630502 0.89112477 0.92438252]]
Producto punto:
 [[2.16283404 2.56721075 2.68385252 1.911198  ]
 [0.92546758 0.48917548 0.65295843 0.47579694]
 [1.29621408 1.63761709 1.79647802 1.37469668]]
Multiplicación:
 [[2.16283404 2.56721075 2.68385252 1.911198  ]
 [0.92546758 0.48917548 0.65295843 0.47579694]
 [1.29621408 1.63761709 1.79647802 1.37469668]]


---

## Pandas

### **Ejercicio 1**
Vamos a utilizar el archivo CSV contenido en el zip coches-dataset.zip dentro del repositorio, en la carpeta sessions/20230104.

Escribir un programa que cargue el dataframe y muestre:
1. Las primeras 10 filas
2. Las últimas 10 filas
3. 10 filas al azar

In [ ]:
# Ejercicio 1

import pandas as pd

df = pd.read_csv('sample_data/coches-de-segunda-mano-sample.csv')

print("Primeras 10 filas:")
df.head(10)


Primeras 10 filas:


url                           company  \
0  e158ae0ca53119ca199c28c36b5c2fcd  9881bcdd5a0ad4733037b3fb25e69c3a   
1  ff267ebb7e700246f47f84f3db660b4b  9881bcdd5a0ad4733037b3fb25e69c3a   
2  de4b02db28ea7786c622b969be10c7c7  9881bcdd5a0ad4733037b3fb25e69c3a   
3  0449972a4d07594acf92e9a7dd28b39c  9881bcdd5a0ad4733037b3fb25e69c3a   
4  12c4fa49bd4fdf23f19ecf396d3f02ef  9881bcdd5a0ad4733037b3fb25e69c3a   
5  f15e9a256de698bf0588753e7add0fdf  9881bcdd5a0ad4733037b3fb25e69c3a   
6  517b8f7c488d9d4645f76b1611418a4e  9881bcdd5a0ad4733037b3fb25e69c3a   
7  2ad681959d278f32a83c3ad7be35443e  9881bcdd5a0ad4733037b3fb25e69c3a   
8  3cb810cd0cd871eb6d5c38832f5f8beb  9881bcdd5a0ad4733037b3fb25e69c3a   
9  13b881bdd31a0387edd64edd726e8c93  9881bcdd5a0ad4733037b3fb25e69c3a   

         make            model  \
0        SEAT           Toledo   
1     CITROEN               C1   
2        FORD  Transit Connect   
3  VOLKSWAGEN        Caravelle   
4        FORD          Transit   
5     PEUGEOT             3008   
6  LAND-ROVER  Discovery Sport   
7       HONDA            Civic   
8     CITROEN         Berlingo   
9      NISSAN             NOTE   

                                             version  price  price_financed  \
0                                   SEAT Toledo  4p.    950             NaN   
1             CITROEN C1 PureTech 60KW 82CV Feel 5p.   6200             NaN   
2  FORD Transit Connect Van 1.5 TDCi 100cv Ambien...   7851          7024.0   
3  VOLKSWAGEN Caravelle Largo 2.0 TDI 140 Comfort...  19426             NaN   
4  FORD Transit 350 96kW L4 Ambiente Propulsion T...  22850         22800.0   
5         PEUGEOT 3008 Style 1.2 PureTech 130 SS 5p.  11490         10490.0   
6  LAND-ROVER Discovery Sport 2.0L TD4 110kW 150C...  28500         26220.0   
7                    HONDA Civic 2.2 iDTEC Sport 5p.   8200             NaN   
8  CITROEN Berlingo Multispace 20 Aniv. PureTech ...  12100             NaN   
9  NISSAN NOTE 5p. 1.2G 80CV Acenta NissanConnect...   6300             NaN   

       fuel    year     kms  ...  doors       shift   color photos  \
0    Diésel  2000.0  227000  ...      4      Manual   Verde      5   
1  Gasolina  2017.0   50071  ...      5      Manual  Blanco      6   
2    Diésel  2016.0  103000  ...      4      Manual  Blanco     10   
3    Diésel  2014.0  120000  ...      4      Manual  Blanco      9   
4    Diésel  2017.0  107000  ...      2      Manual  Blanco      4   
5  Gasolina  2016.0   78665  ...      5      Manual  Blanco     32   
6    Diésel  2017.0   36238  ...      5  Automático  Blanco     47   
7    Diésel  2012.0  203000  ...      5      Manual  Blanco     15   
8  Gasolina  2018.0   45000  ...      5      Manual    Azul      6   
9  Gasolina  2016.0   77000  ...      5      Manual  Blanco      6   

   is_professional                            dealer   province country  \
0            False  0f4bb8455d27349b8273109b66a847f3    Navarra   Spain   
1             True                     Autos Raymara   Tenerife   Spain   
2             True                           Auto 96  Barcelona   Spain   
3             True                          Inniauto    Navarra   Spain   
4             True              Autofleet España,s.l    Sevilla   Spain   
5             True                    Flexicar Rivas     Madrid   Spain   
6             True                           OK Cars   Baleares   Spain   
7            False  001783c2b59526bb858210edffa68c6b  Barcelona   Spain   
8            False  f7cb72400bd7fb19294e1f9692c48cd9   Alicante   Spain   
9            False  8a3b0eb4d055a275274895319688e80a  Barcelona   Spain   

          publish_date          insert_date  
0  2020-12-18 10:47:13  2021-01-15 00:00:00  
1  2021-01-02 11:25:40  2021-01-15 00:00:00  
2  2020-12-16 10:51:45  2021-01-15 00:00:00  
3  2020-11-25 11:09:14  2021-01-15 00:00:00  
4  2021-01-12 20:00:34  2021-01-15 00:00:00  
5  2021-01-08 17:03:33  2021-01-15 00:00:00  
6  2021-01-12 11:26:18  2021-01-15 00:00:00  
7  2020-12-03 15:3

In [ ]:
print("Últimas 10 filas:")
df.tail(10)

Últimas 10 filas:


url                           company  \
49990  22c3253f7acac12eda1784ef4ce901d4  9881bcdd5a0ad4733037b3fb25e69c3a   
49991  0c78cec43f04e25e391b8c15b393fbf4  9881bcdd5a0ad4733037b3fb25e69c3a   
49992  484b780d2f492b6c481a78c975b8f59e  9881bcdd5a0ad4733037b3fb25e69c3a   
49993  2b9bb09716f01a9496f08805dc09c08e  9881bcdd5a0ad4733037b3fb25e69c3a   
49994  f6caffb1207bc61d62baa2759cd0a10b  9881bcdd5a0ad4733037b3fb25e69c3a   
49995  730210734bfbe1d3df878d5df71246f2  9881bcdd5a0ad4733037b3fb25e69c3a   
49996  732b04fb47dd9559dbdcd099c5af484e  9881bcdd5a0ad4733037b3fb25e69c3a   
49997  c10afb53957fb8012707239bdfa66018  9881bcdd5a0ad4733037b3fb25e69c3a   
49998  f74363a6688ba11b71b4d980a959b8d3  9881bcdd5a0ad4733037b3fb25e69c3a   
49999  3d60801ccb96ef038747130e8a34ceda  9881bcdd5a0ad4733037b3fb25e69c3a   

          make    model                                            version  \
49990   SUBARU  Outback                    SUBARU Outback 2.5i Limited 5p.   
49991  PORSCHE      911                 PORSCHE 911 Turbo Coupe A.M.08 2p.   
49992     JEEP  Compass          JEEP Compass 1.4 Mair 103kW Sport 4x2 5p.   
49993     SEAT     León  SEAT Leon ST 1.8 TSI 132kW 180CV StSp FR Plus 5p.   
49994     SEAT     León  SEAT Leon ST 1.6 TDI 85kW 115CV StSp Style Ed 5p.   
49995  HYUNDAI      i30        HYUNDAI i30 1.4 TGDI Tecno Fastback DCT 5p.   
49996  RENAULT   Laguna  RENAULT Laguna Coupe Limited 2.0 Energy dCi 15...   
49997  PEUGEOT      108           PEUGEOT 108 TOP Allure VTi 52kW 72CV 5p.   
49998     AUDI      RS4           AUDI RS4 Avant 4.2 FSI 450cv quattro 5p.   
49999  CITROEN       C2                    CITROEN C2 1.4 HDI VTR Plus 3p.   

       price  price_financed      fuel    year     kms  ...  doors  \
49990   9800             NaN  Gasolina  2012.0  118000  ...      5   
49991  67900             NaN  Gasolina  2008.0   99000  ...      2   
49992  21900             NaN  Gasolina  2020.0    5000  ...      5   
49993  19490         18490.0  Gasolina  2017.0   67900  ...      5   
49994  18590         16590.0    Diésel  2019.0   21153  ...      5   
49995  18490         16490.0  Gasolina  2018.0   47000  ...      5   
49996  14500         13551.0    Diésel  2015.0   68750  ...      2   
49997  11000          9000.0  Gasolina  2019.0   21422  ...      5   
49998  47900             NaN  Gasolina  2013.0   47900  ...      5   
49999   2790             NaN    Diésel  2006.0  106000  ...      3   

            shift                           color photos  is_professional  \
49990  Automático                    Gris / Plata      6            False   
49991  Automático                            Rojo     54             True   
49992      Manual                    Gris / Plata     29             True   
49993      Manual                          Blanco     34             True   
49994      Manual                    Gris / Plata     20             True   
49995  Automático                    Gris / Plata     26             True   
49996      Manual  KNG Gris Casiopea (metalizado)     30             True   
49997      Manual                    Gris / Plata     17             True   
49998  Automático        Gris / Plata (Antracita)     20             True   
49999      Manual                           Negro     21             True   

                                 dealer   province country  \
49990  6e55c8f1af9646ada8d52ca37d627d42   Tenerife   Spain   
49991                      Quality Cars   Valencia   Spain   
49992                           AJ CARS    Navarra   Spain   
49993                Flexicar Barcelona  Barcelona   Spain   
49994       Das Weltauto Gil Automocion     Madrid   Spain   
49995                   Flexicar Málaga     Málaga   Spain   
49996                      Ocasion Plus     Málaga   Spain   
49997                 Psa Retail Huelva     Huelva   Spain   
49998                    Codigocar Lugo       Lugo   Spain   
49999                   AUTOVALENCIA 19  Barcelona   Spain   

              publish_date 

In [ ]:
print("10 filas al azar:")
df.sample(10)

10 filas al azar:


url                           company  \
35906  35943dae690fbcf71ef238ac6a40545c  9881bcdd5a0ad4733037b3fb25e69c3a   
42679  88f913c39e9aef53608a4b46f0ef6f10  9881bcdd5a0ad4733037b3fb25e69c3a   
13079  d80390e73b2acb34d4cca2b3087c152c  9881bcdd5a0ad4733037b3fb25e69c3a   
29999  9b897903b274a3fa257133ede1e6ec2c  9881bcdd5a0ad4733037b3fb25e69c3a   
49802  39e9362c2570ba1a2c097f637f9df45f  9881bcdd5a0ad4733037b3fb25e69c3a   
42787  9478a597b506e002ab7d5b447d773420  9881bcdd5a0ad4733037b3fb25e69c3a   
31672  f5da4e869be4f031e4236ac06d637ab8  9881bcdd5a0ad4733037b3fb25e69c3a   
1250   94fc7b4a0af33c35b9ed653ffa682178  9881bcdd5a0ad4733037b3fb25e69c3a   
26388  4dc80a4640763cb3d0d038fe6e6b4996  9881bcdd5a0ad4733037b3fb25e69c3a   
11557  acd91ef3df29d5536dabb75ddb5692df  9881bcdd5a0ad4733037b3fb25e69c3a   

             make              model  \
35906       MAZDA             Mazda3   
42679       VOLVO                S40   
13079         BMW                 X1   
29999        SEAT              Ibiza   
49802     CITROEN           C4 Sedán   
42787  VOLKSWAGEN             Passat   
31672  LAND-ROVER  Range Rover Sport   
1250       TOYOTA              Hilux   
26388        AUDI                 A3   
11557        FORD             Mondeo   

                                                 version  price  \
35906               MAZDA Mazda3 1.6 VVT 105cv Style 5p.   5990   
42679                     VOLVO S40 1.6 DRIVe Summum 4p.   5200   
13079                               BMW X1 sDrive16d 5p.  15500   
29999                 SEAT Ibiza SC 1.4 TDI 105cv FR 3p.  11900   
49802           CITROEN C4 Sedan 1.6i 16v Collection 4p.   4500   
42787  VOLKSWAGEN Passat 2.0 TDI 140cv DPF DSG Highli...   7500   
31672     LAND-ROVER Range Rover Sport 2.7 TD V6 HSE 5p.  17400   
1250        TOYOTA Hilux 2.4 D4D Cabina Doble VX 4x4 4p.  28500   
26388   AUDI A3 Sedan 1.6 TDI clean 110CV Attraction 4p.  13999   
11557  FORD Mondeo 2.0 Hibrido 137kW 187CV Titanium H...  21900   

       price_financed      fuel    year     kms  ...  doors       shift  \
35906             NaN  Gasolina  2010.0  150000  ...      5      Manual   
42679             NaN    Diésel  2010.0  170000  ...      4      Manual   
13079             NaN    Diésel  2016.0  150000  ...      5      Manual   
29999         11500.0    Diésel  2016.0   81000  ...      3      Manual   
49802             NaN  Gasolina  2009.0   50000  ...      4      Manual   
42787             NaN    Diésel  2010.0  182000  ...      4  Automático   
31672             NaN    Diésel  2007.0  142960  ...      5  Automático   
1250              NaN    Diésel  2017.0   35000  ...      4      Manual   
26388             NaN    Diésel  2015.0  143000  ...      4      Manual   
11557         20700.0   Híbrido  2018.0   38500  ...      4  Automático   

                              color photos  is_professional  \
35906                          Azul     12             True   
42679                        Blanco      9            False   
13079                        Blanco      8            False   
29999                        Blanco     22             True   
49802                        Blanco      8            False   
42787  Negro (Interior Cuero Beige)     17             True   
31672                        Blanco     28             True   
1250                   Gris / Plata     14             True   
26388                  Gris / Plata     13             True   
11557                          Rojo     18             True   

                                 dealer   province country  \
35906                    Alberto Alonso  Barcelona   Spain   
42679  2bba1f8214e7b0b5fe6f9fce04d76900  Barcelona   Spain   
13079  098a50f333b9fc79b806dd51ed4ea859   Alicante   Spain   
29999           AUTOGALLERY PREMIUM S.L     Madrid   Spain   
49802  0a2fc20eebb8ba290b21c35a0e5c5a80  Barcelona   Spain   
42787                       Cars Madrid     Madrid   Spain   
31672                      C&C Carsales     Málaga   Sp

### **Ejercicio 2**
Escribir un programa que a partir del dataframe definido en el **ejercicio 6**, nos muestre el tamaño del dataframe, el tipo de datos que contiene y su uso en memoria, y un breve resumen de los datos contenidos en cada columna.

In [ ]:
# Ejercicio 2

print("Tamaño del dataframe:")
df.size


Tamaño del dataframe:


1050000

In [ ]:
print("Información del dataframe (tipos de datos y uso de memoria):")
df.info()

Información del dataframe (tipos de datos y uso de memoria):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 21 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   url              50000 non-null  object 
 1   company          50000 non-null  object 
 2   make             49998 non-null  object 
 3   model            49995 non-null  object 
 4   version          50000 non-null  object 
 5   price            50000 non-null  int64  
 6   price_financed   23563 non-null  float64
 7   fuel             49954 non-null  object 
 8   year             49998 non-null  float64
 9   kms              50000 non-null  int64  
 10  power            41472 non-null  float64
 11  doors            50000 non-null  int64  
 12  shift            49889 non-null  object 
 13  color            49406 non-null  object 
 14  photos           50000 non-null  int64  
 15  is_professional  50000 non-null  bool   
 1

In [ ]:
print("Datos por columna:")
df.describe()

Datos por columna:


price  price_financed          year           kms  \
count   50000.000000    23563.000000  49998.000000  5.000000e+04   
mean    15166.270260    18480.029283   2012.311032  1.163591e+05   
std     16485.669747    13389.800738      6.677760  1.072921e+05   
min       300.000000      700.000000   1970.000000  0.000000e+00   
25%      5500.000000    10790.000000   2007.000000  3.830000e+04   
50%     11750.000000    15500.000000   2015.000000  9.999900e+04   
75%     19800.000000    21995.000000   2018.000000  1.749000e+05   
max    549900.000000   428999.000000   2021.000000  5.000000e+06   

              power         doors        photos  
count  41472.000000  50000.000000  50000.000000  
mean     146.396388      4.505380     16.199120  
std       71.283964      0.868001     12.422882  
min       29.000000      2.000000      0.000000  
25%      109.000000      4.000000      7.000000  
50%      130.000000      5.000000     13.000000  
75%      163.000000      5.000000     23.000000  
max      800.000000      5.000000     54.000000

### **Ejercicio 3**
Escribir un programa que a partir del dataframe definido en el **ejercicio 6** nos muestre los coches que se encuentran por debajo de 5000 euros de la marca Volkswagen

In [ ]:
# Ejercicio 3

df.query("make == 'VOLKSWAGEN' and price < 5000")

url                           company  \
11     8dadc0a13657e83e90a972e74456f701  9881bcdd5a0ad4733037b3fb25e69c3a   
12     254023385c971f3854bbbb2f65b475e8  9881bcdd5a0ad4733037b3fb25e69c3a   
23     ad1cd419582b0ee1617498592ba55dd8  9881bcdd5a0ad4733037b3fb25e69c3a   
65     b21b779ae2ffa8cbdebf75ef0e12a9ef  9881bcdd5a0ad4733037b3fb25e69c3a   
83     f240ef4476f35b23a9390693f4c5fd97  9881bcdd5a0ad4733037b3fb25e69c3a   
...                                 ...                               ...   
49708  68115c3c64779a65527cdae21b36313f  9881bcdd5a0ad4733037b3fb25e69c3a   
49752  555c66ec619b4ca865aaf8b712c60d84  9881bcdd5a0ad4733037b3fb25e69c3a   
49875  cb9851d79ee91aaed7895dd7cb194a6f  9881bcdd5a0ad4733037b3fb25e69c3a   
49908  5408fcd9a37144f6d23d3c8370f4a6f9  9881bcdd5a0ad4733037b3fb25e69c3a   
49965  c8b8e7ec796d945f0446c8d26c122ecf  9881bcdd5a0ad4733037b3fb25e69c3a   

             make        model                                      version  \
11     VOLKSWAGEN         Golf                         VOLKSWAGEN Golf  3p.   
12     VOLKSWAGEN         Polo        VOLKSWAGEN Polo 75 Trendline Auto 3p.   
23     VOLKSWAGEN      Phaeton                      VOLKSWAGEN Phaeton  5p.   
65     VOLKSWAGEN         Golf                         VOLKSWAGEN Golf  5p.   
83     VOLKSWAGEN       Passat  VOLKSWAGEN Passat 2.0 TDI 140cv Advance 4p.   
...           ...          ...                                          ...   
49708  VOLKSWAGEN       Passat                       VOLKSWAGEN Passat  4p.   
49752  VOLKSWAGEN  Transporter                  VOLKSWAGEN Transporter  5p.   
49875  VOLKSWAGEN       Passat  VOLKSWAGEN Passat 2.0 TDI 140cv Advance 4p.   
49908  VOLKSWAGEN         Golf                         VOLKSWAGEN Golf  2p.   
49965  VOLKSWAGEN         Polo                                   VOLKSWAGEN   

       price  price_financed      fuel    year     kms  ...  doors  \
11      1700             NaN    Diésel  1990.0  350000  ...      3   
12      1300             NaN  Gasolina  2001.0  217000  ...      3   
23      3750             NaN    Diésel  2006.0     400  ...      5   
65      4800             NaN    Diésel  2007.0  213000  ...      5   
83      3400             NaN    Diésel  2006.0  272000  ...      4   
...      ...             ...       ...     ...     ...  ...    ...   
49708   3500             NaN  Gasolina  2007.0  300100  ...      4   
49752   1950             NaN    Diésel  1994.0  500000  ...      5   
49875   4990          4990.0    Diésel  2006.0  165000  ...      4   
49908    800             NaN  Gasolina  1994.0  200000  ...      2   
49965   1600             NaN  Gasolina  2005.0  199700  ...      3   

            shift         color photos  is_professional  \
11         Manual          Rojo      4            False   
12         Manual          Azul      1            False   
23     Automático         Verde      9            False   
65         Manual         Negro      7            False   
83         Manual  Gris / Plata      9             True   
...           ...           ...    ...              ...   
49708      Manual           NaN      9            False   
49752      Manual        Blanco      9            False   
49875      Manual  Gris / Plata      1             True   
49908      Manual          Azul      5            False   
49965      Manual  Gris / Plata      0            False   

                                 dealer   province country  \
11     a425a46b14a78f533e40e974b3d31385  Guipúzcoa   Spain   
12     a96e8f71351fbe70573b70189c0dd2bb  Barcelona   Spain   
23     647431b5ca55b04fdf3c2fce31ef1915     Madrid   Spain   
65     a94652aa97c7211ba8954dd15a3cf838    Almería   Spain   
83                                 RAUL     Madrid   Spain   
...                                 ...        ...     ...   
49708  ab02fceb9689114b1cd1844e456c0695    Vizcaya   Spain   
49752  a208a1dbed72a7c5f6b0c8c660c75766   Alicante   Spain   
49875                          Dv Motor     Málaga   S

### **Ejercicio 4**
Escribir un programa que a partir del dataframe definido en el **ejercicio 6** nos muestre los 10 coches más nuevos que sean híbridos enchufables y cuesten menos de 10000 euros.

In [ ]:
# Ejercicio 4

df.query("fuel == 'Híbrido' and price < 10000").sort_values(by='year', ascending=False).head(10)

url                           company  \
43715  0fc45bdb038d9fea6eba797e810e9678  9881bcdd5a0ad4733037b3fb25e69c3a   
7573   ea4a5730aff380dc01be467acd8b6bb3  9881bcdd5a0ad4733037b3fb25e69c3a   
1402   0549b321beb106b82d2528552a208be2  9881bcdd5a0ad4733037b3fb25e69c3a   
33547  7059c846f8ccdbd5821601eb1bd62006  9881bcdd5a0ad4733037b3fb25e69c3a   
35981  8d79d589cd789cfeda9fe5128b6a7f69  9881bcdd5a0ad4733037b3fb25e69c3a   
6577   3b06f48f1b7b5877e9fb0d2bb60dc7e1  9881bcdd5a0ad4733037b3fb25e69c3a   
44769  325e3123db500eba1823235a57604a52  9881bcdd5a0ad4733037b3fb25e69c3a   
32608  170552982cb781b1ce97b0aa5ad0f80e  9881bcdd5a0ad4733037b3fb25e69c3a   
14289  e5f47a776ca4db1318bff10f345ed13c  9881bcdd5a0ad4733037b3fb25e69c3a   
33671  8274d4ced151f213dde956c645a9ae15  9881bcdd5a0ad4733037b3fb25e69c3a   

         make  model                             version  price  \
43715  TOYOTA  Yaris  TOYOTA Yaris 1.5 Hybrid Active 5p.   9999   
7573   TOYOTA  Yaris  TOYOTA Yaris 1.5 Hybrid Active 5p.   7499   
1402   TOYOTA  Yaris  TOYOTA Yaris 1.5 Hybrid Active 5p.   8850   
33547  TOYOTA  Yaris      TOYOTA Yaris Hybrid Active 5p.   9995   
35981  TOYOTA  Yaris        TOYOTA Yaris Hybrid City 5p.   8256   
6577   TOYOTA  Yaris    TOYOTA Yaris 1.5 Hybrid City 5p.   8500   
44769  TOYOTA  Yaris    TOYOTA Yaris 1.5 Hybrid City 5p.   9295   
32608  TOYOTA  Yaris    TOYOTA Yaris 1.5 Hybrid City 5p.   9900   
14289  TOYOTA  Yaris  TOYOTA Yaris 1.5 Hybrid Active 5p.   9250   
33671  TOYOTA  Yaris      TOYOTA Yaris Hybrid Active 5p.   9990   

       price_financed     fuel    year     kms  ...  doors       shift  \
43715             NaN  Híbrido  2017.0   99126  ...      5  Automático   
7573           6999.0  Híbrido  2017.0  230000  ...      5  Automático   
1402           8350.0  Híbrido  2016.0  144753  ...      5  Automático   
33547             NaN  Híbrido  2016.0   40000  ...      5  Automático   
35981          7100.0  Híbrido  2016.0   60050  ...      5  Automático   
6577           8500.0  Híbrido  2016.0  212000  ...      5  Automático   
44769          7795.0  Híbrido  2016.0   78706  ...      5      Manual   
32608          9300.0  Híbrido  2016.0   77000  ...      5  Automático   
14289          8645.0  Híbrido  2016.0  121422  ...      5  Automático   
33671          8990.0  Híbrido  2015.0  111462  ...      5  Automático   

                color photos  is_professional  \
43715            Rojo     16            False   
7573           Blanco     35             True   
1402           Blanco     29             True   
33547          Blanco     13             True   
35981          Blanco     21             True   
6577           Blanco     30             True   
44769          Blanco     44             True   
32608          Blanco      9             True   
14289  Blanco (*LRO*)     25             True   
33671          Blanco     39             True   

                                 dealer    province country  \
43715  630be0569d4f447db7aff29a10890568   Barcelona   Spain   
7573         Uta Automóviles de Ocasión      Madrid   Spain   
1402                   Dosauto Garantía     Sevilla   Spain   
33547                          Vehincar  Las Palmas   Spain   
35981                         Bamosauto      Madrid   Spain   
6577                    AUTOGEST Málaga      Málaga   Spain   
44769                        VALENCIA-C   Castellón   Spain   
32608                       Ocasionauto      Madrid   Spain   
14289                      Ocasion Plus    Albacete   Spain   
33671                Flexicar Barcelona   Barcelona   Spain   

              publish_date          insert_date  
43715  2021-01-08 17:53:42  2021-01-15 00:00:00  
7573   2021-01-14 09:53:48  2021-01-15 00:00:00  
1402   2020-12-29 18:14:36  2021-01-15 00:00:00  
33547  2021-01-05 17:40:40  2021-01-15 00:00:00  
35981  2021-01-08 18:35:11  2021-01-15 00:00:00  
6577   2021-01-13 22:56:29  2021-01-15 00:00:00  
44769  2020-12-30 13:34:21  2021-01-15 00:00:00  
3

## **Ejercicio 5**
Escribir un programa que a partir del dataframe definido en el **ejercicio 6** nos calcule una nueva columna con el ahorro porcentual con respecto al precio base de financiar el coche.

In [ ]:
# Ejercicio 5

df['savings_pct'] = round(((df['price'] - df['price_financed']) * 100) / df['price'], 2)
df.sort_values(by='savings_pct', ascending=False).head(10)


url                           company  \
40732  744475da4d021cd481cf2dcc30ca9c16  9881bcdd5a0ad4733037b3fb25e69c3a   
49118  30938910a5d3242214ab3addc0421cf9  9881bcdd5a0ad4733037b3fb25e69c3a   
10264  4540a074f85e6f3ac963e5c0d4787bc9  9881bcdd5a0ad4733037b3fb25e69c3a   
28246  8d830d6b52a9a3dc4683b1c7b1775dda  9881bcdd5a0ad4733037b3fb25e69c3a   
46994  5aab27edd4a86621f0c5896a2b543159  9881bcdd5a0ad4733037b3fb25e69c3a   
47381  8a977f80434300e8c0bc235e93cb8f50  9881bcdd5a0ad4733037b3fb25e69c3a   
5659   75089cde3b8f3aacad6746c213cd4e88  9881bcdd5a0ad4733037b3fb25e69c3a   
1045   e6a382f3f6f6532ecb0e671089499edb  9881bcdd5a0ad4733037b3fb25e69c3a   
15341  2ec09b7ee027e426a9745296ec2706e4  9881bcdd5a0ad4733037b3fb25e69c3a   
7951   49f5e24e551160c667316d0a07773283  9881bcdd5a0ad4733037b3fb25e69c3a   

          make   model                                           version  \
40732  CITROEN  C-Zero                       CITROEN CZero Seduction 5p.   
49118   NISSAN   Micra      NISSAN Micra IGT 74 kW 100 CV E6D Acenta 5p.   
10264   NISSAN   Micra      NISSAN Micra IGT 74 kW 100 CV E6D Acenta 5p.   
28246  PEUGEOT     208         PEUGEOT 208 5P STYLE 1.2L PureTech 82 5p.   
46994   ABARTH    500C  ABARTH 500C 1.4 16v TJet 595 107kW 145CV E6D 2p.   
47381      NaN     D2S                                      D2S 27kW 3p.   
5659       NaN     D2S                                      D2S 27kW 3p.   
1045   PEUGEOT     108              PEUGEOT 108 Allure VTi 52kW 72CV 5p.   
15341     FIAT     500           FIAT 500 1.2 8v 69 CV Color Therapy 3p.   
7951      FIAT     500           FIAT 500 1.2 8v 69 CV Color Therapy 3p.   

       price  price_financed       fuel    year    kms  ...       shift  \
40732  22500         12900.0  Eléctrico  2020.0     10  ...  Automático   
49118  18275         11200.0   Gasolina  2020.0      0  ...      Manual   
10264  18275         11200.0   Gasolina  2020.0      0  ...      Manual   
28246   9900          6400.0   Gasolina  2016.0  71092  ...      Manual   
46994  26410         17400.0   Gasolina  2020.0      0  ...      Manual   
47381  21495         14495.0  Eléctrico  2021.0      6  ...  Automático   
5659   21495         14495.0  Eléctrico  2021.0      3  ...  Automático   
1045   11500          8000.0   Gasolina  2018.0  12301  ...      Manual   
15341   9999          6999.0   Gasolina  2014.0  43878  ...      Manual   
7951    9999          6999.0   Gasolina  2014.0  43878  ...      Manual   

              color photos is_professional  \
40732  Gris / Plata     22            True   
49118         Beige     11            True   
10264         Beige     12            True   
28246          Rojo     11            True   
46994        Blanco     15            True   
47381          Azul     15            True   
5659          Beige     16            True   
1045   Gris / Plata     18            True   
15341          Rojo     29            True   
7951           Rojo     29            True   

                                         dealer  province country  \
40732                         Garaje Las Flores  Albacete   Spain   
49118                            NISSAN ALMENAR  Valencia   Spain   
10264                            NISSAN ALMENAR  Alicante   Spain   
28246         PSA Retail Valencia - Tres Cruces  Valencia   Spain   
46994                                  Motordos   Granada   Spain   
47381                             GJ AUTOMOTIVE    Burgos   Spain   
5659                              GJ AUTOMOTIVE    Burgos   Spain   
1045          PSA Retail Valencia - Tres Cruces  Valencia   Spain   
15341                          Antón Automoción   Vizcaya   Spain   
7951   Concesión Oficial Citroën Álava Lascaray     Álava   Spain   

              publish_date          insert_date savings_pct  
40732  2020-12-28 23:27:21  2021-01-15 00:00:00       42.67  
49118  2020-12-27 14:13:42  2021-01-15 00:00:00       38.71  
10264  2020-12-23 13:05:04  2021-01-15 00:00:00       38.71  
28246  202