<style type="text/css">
    ol { list-style-type: upper-alpha; }
</style>

<center> <img src=https://i.imgur.com/0TSSaqL.png width="550"> </center>

<center> <h3> Module 3: Programación en Python </h3> </center>
<center> <h4> Sesiones síncronas - 20230104 - 2/2</h4> </center>

## Numpy

In [2]:
import numpy as np

### **Ejercicio 1**

Escribir un programa que cree:
1. Un array vacío
2. Un array de ceros
3. Un array de valores 1 a 5
4. Una matriz diagonal de valores 1 a 5

Y nos muestre por cada uno de ellos sus dimensiones y el número de elementos que contiene.

In [ ]:
# Ejercicio 1
arrays = [
    np.empty((3, 5)),
    np.zeros((3, 4)),
    np.arange(1, 6),
    np.diag(list(range(1, 6)))
]

for ar in arrays:
  print("Array: \n", ar)
  print(" -- Dimensión:", ar.shape)
  print(" -- Número de elementos:", ar.size)
  print("----------------------------------------")

Array: 
 [[1.8588378e-316 0.0000000e+000 0.0000000e+000 0.0000000e+000
  0.0000000e+000]
 [0.0000000e+000 0.0000000e+000 0.0000000e+000 0.0000000e+000
  0.0000000e+000]
 [0.0000000e+000 0.0000000e+000 0.0000000e+000 0.0000000e+000
  0.0000000e+000]]
 -- Dimensión: (3, 5)
 -- Número de elementos: 15
----------------------------------------
Array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
 -- Dimensión: (3, 4)
 -- Número de elementos: 12
----------------------------------------
Array: 
 [1 2 3 4 5]
 -- Dimensión: (5,)
 -- Número de elementos: 5
----------------------------------------
Array: 
 [[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]
 -- Dimensión: (5, 5)
 -- Número de elementos: 25
----------------------------------------


### **Ejercicio 2**
Escribir un programa que, dados dos arrays, lleve a cabo:
1. La unión
2. La intersección
3. La suma
4. La multiplicación por un valor constante


In [ ]:
# Ejercicio 2
a = np.array([1.53, 3.22])
b = np.array([7.334, 3.22])

print("Unión:", np.concatenate([a, b]))
print("Intersección:", np.intersect1d(a, b))
print("Suma:", a + b)
print("Multiplicación por una constante n = 3:", a * 3)

Unión: [1.53  3.22  7.334 3.22 ]
Intersección: [3.22]
Suma: [8.864 6.44 ]
Multiplicación por una constante n = 3: [4.59 9.66]


## Ejercicio 3
Escribir un programa que dados dos arrays los compare.

In [ ]:
# Ejercicio 3
a = np.array([5.445, 1.22])
b = np.array([19.56, 1.12])
print("Array a: ", a)
print("Array b: ", b)
print("a > b", np.greater(a, b))
print("a >= b", np.greater_equal(a, b))
print("a < b", np.less(a, b))
print("a <= b", np.less_equal(a, b))

Array a:  [5.445 1.22 ]
Array b:  [19.56  1.12]
a > b [False  True]
a >= b [False  True]
a < b [ True False]
a <= b [ True False]


### **Ejercicio 4**
Escribir un programa que cree un array de temperaturas en grados fahrenheit y transforme todos sus elementos a grados centígrados. Recordad que la fórmula utilizada para la conversión es:
\begin{equation}
C = \frac{5}{{9}} \left(F - 32 \right)
\end{equation}

In [3]:
# Ejercicio 4
grados_fahrenheit = np.array([67.34, -11.11, 78.96, 1.11, 102.71, 0])
print(
    "El array de grados Fahrenheit:\n", grados_fahrenheit, 
    "\npasa a ser:\n", np.round(((5/9) * (grados_fahrenheit - 32)), 2), 
    "\nen grados Celsius.")

El array de grados Fahrenheit:
 [ 67.34 -11.11  78.96   1.11 102.71   0.  ] 
pasa a ser:
 [ 19.63 -23.95  26.09 -17.16  39.28 -17.78] 
en grados Celsius.


### **Ejercicio 5**
Escribir un programa que cree una matriz de dimensión 3x5 y otra de dimensión 5x4, con valores aleatorios, y calcule su multiplicación.

In [ ]:
# Ejercicio 5
x = np.random.random((3, 5))
y = np.random.random((5, 4))
print("Primer array:\n", x)
print("Segundo array:\n", y)
print("\nProducto de dos arrays:\n", np.dot(x, y))

Primer array:
 [[0.91652277 0.3302544  0.52377514 0.87955835 0.44359562]
 [0.5222592  0.4949982  0.60076647 0.85297609 0.43132347]
 [0.9477568  0.06499711 0.69660781 0.96864871 0.83225279]]
Segundo array:
 [[0.98942443 0.98308916 0.90232    0.40146514]
 [0.75704319 0.36229086 0.20916088 0.80655511]
 [0.40473534 0.73398236 0.51698771 0.50831828]
 [0.71414226 0.47325351 0.23960748 0.48210836]
 [0.71201114 0.78461    0.06728893 0.27412189]]

Producto de dos arrays:
 [[2.31281199 2.16941711 1.40745628 1.4462065 ]
 [2.05087584 1.87580731 1.11877081 1.44375487]
 [2.5532074  2.57798541 1.51700933 1.48214589]]


---

## Pandas

In [ ]:
import pandas as pd
data = pd.read_csv("coches-de-segunda-mano-sample.csv")

### **Ejercicio 6**
Vamos a utilizar el archivo CSV contenido en el zip coches-dataset.zip dentro del repositorio, en la carpeta sessions/20230104.

Escribir un programa que cargue el dataframe y muestre:
1. Las primeras 10 filas
2. Las últimas 10 filas
3. 10 filas al azar

In [ ]:
# Ejercicio 6
print("10 primeras filas:")
data.head(n = 10)

10 primeras filas:


url                           company  \
0  e158ae0ca53119ca199c28c36b5c2fcd  9881bcdd5a0ad4733037b3fb25e69c3a   
1  ff267ebb7e700246f47f84f3db660b4b  9881bcdd5a0ad4733037b3fb25e69c3a   
2  de4b02db28ea7786c622b969be10c7c7  9881bcdd5a0ad4733037b3fb25e69c3a   
3  0449972a4d07594acf92e9a7dd28b39c  9881bcdd5a0ad4733037b3fb25e69c3a   
4  12c4fa49bd4fdf23f19ecf396d3f02ef  9881bcdd5a0ad4733037b3fb25e69c3a   
5  f15e9a256de698bf0588753e7add0fdf  9881bcdd5a0ad4733037b3fb25e69c3a   
6  517b8f7c488d9d4645f76b1611418a4e  9881bcdd5a0ad4733037b3fb25e69c3a   
7  2ad681959d278f32a83c3ad7be35443e  9881bcdd5a0ad4733037b3fb25e69c3a   
8  3cb810cd0cd871eb6d5c38832f5f8beb  9881bcdd5a0ad4733037b3fb25e69c3a   
9  13b881bdd31a0387edd64edd726e8c93  9881bcdd5a0ad4733037b3fb25e69c3a   

         make            model  \
0        SEAT           Toledo   
1     CITROEN               C1   
2        FORD  Transit Connect   
3  VOLKSWAGEN        Caravelle   
4        FORD          Transit   
5     PEUGEOT             3008   
6  LAND-ROVER  Discovery Sport   
7       HONDA            Civic   
8     CITROEN         Berlingo   
9      NISSAN             NOTE   

                                             version  price  price_financed  \
0                                   SEAT Toledo  4p.    950             NaN   
1             CITROEN C1 PureTech 60KW 82CV Feel 5p.   6200             NaN   
2  FORD Transit Connect Van 1.5 TDCi 100cv Ambien...   7851          7024.0   
3  VOLKSWAGEN Caravelle Largo 2.0 TDI 140 Comfort...  19426             NaN   
4  FORD Transit 350 96kW L4 Ambiente Propulsion T...  22850         22800.0   
5         PEUGEOT 3008 Style 1.2 PureTech 130 SS 5p.  11490         10490.0   
6  LAND-ROVER Discovery Sport 2.0L TD4 110kW 150C...  28500         26220.0   
7                    HONDA Civic 2.2 iDTEC Sport 5p.   8200             NaN   
8  CITROEN Berlingo Multispace 20 Aniv. PureTech ...  12100             NaN   
9  NISSAN NOTE 5p. 1.2G 80CV Acenta NissanConnect...   6300             NaN   

       fuel    year     kms  ...  doors       shift   color photos  \
0    Diésel  2000.0  227000  ...      4      Manual   Verde      5   
1  Gasolina  2017.0   50071  ...      5      Manual  Blanco      6   
2    Diésel  2016.0  103000  ...      4      Manual  Blanco     10   
3    Diésel  2014.0  120000  ...      4      Manual  Blanco      9   
4    Diésel  2017.0  107000  ...      2      Manual  Blanco      4   
5  Gasolina  2016.0   78665  ...      5      Manual  Blanco     32   
6    Diésel  2017.0   36238  ...      5  Automático  Blanco     47   
7    Diésel  2012.0  203000  ...      5      Manual  Blanco     15   
8  Gasolina  2018.0   45000  ...      5      Manual    Azul      6   
9  Gasolina  2016.0   77000  ...      5      Manual  Blanco      6   

   is_professional                            dealer   province country  \
0            False  0f4bb8455d27349b8273109b66a847f3    Navarra   Spain   
1             True                     Autos Raymara   Tenerife   Spain   
2             True                           Auto 96  Barcelona   Spain   
3             True                          Inniauto    Navarra   Spain   
4             True              Autofleet España,s.l    Sevilla   Spain   
5             True                    Flexicar Rivas     Madrid   Spain   
6             True                           OK Cars   Baleares   Spain   
7            False  001783c2b59526bb858210edffa68c6b  Barcelona   Spain   
8            False  f7cb72400bd7fb19294e1f9692c48cd9   Alicante   Spain   
9            False  8a3b0eb4d055a275274895319688e80a  Barcelona   Spain   

          publish_date          insert_date  
0  2020-12-18 10:47:13  2021-01-15 00:00:00  
1  2021-01-02 11:25:40  2021-01-15 00:00:00  
2  2020-12-16 10:51:45  2021-01-15 00:00:00  
3  2020-11-25 11:09:14  2021-01-15 00:00:00  
4  2021-01-12 20:00:34  2021-01-15 00:00:00  
5  2021-01-08 17:03:33  2021-01-15 00:00:00  
6  2021-01-12 11:26:18  2021-01-15 00:00:00  
7  2020-12-03 15:3

In [ ]:
print("10 últimas filas:")
data.tail(n = 10)

10 últimas filas:


url                           company  \
49990  22c3253f7acac12eda1784ef4ce901d4  9881bcdd5a0ad4733037b3fb25e69c3a   
49991  0c78cec43f04e25e391b8c15b393fbf4  9881bcdd5a0ad4733037b3fb25e69c3a   
49992  484b780d2f492b6c481a78c975b8f59e  9881bcdd5a0ad4733037b3fb25e69c3a   
49993  2b9bb09716f01a9496f08805dc09c08e  9881bcdd5a0ad4733037b3fb25e69c3a   
49994  f6caffb1207bc61d62baa2759cd0a10b  9881bcdd5a0ad4733037b3fb25e69c3a   
49995  730210734bfbe1d3df878d5df71246f2  9881bcdd5a0ad4733037b3fb25e69c3a   
49996  732b04fb47dd9559dbdcd099c5af484e  9881bcdd5a0ad4733037b3fb25e69c3a   
49997  c10afb53957fb8012707239bdfa66018  9881bcdd5a0ad4733037b3fb25e69c3a   
49998  f74363a6688ba11b71b4d980a959b8d3  9881bcdd5a0ad4733037b3fb25e69c3a   
49999  3d60801ccb96ef038747130e8a34ceda  9881bcdd5a0ad4733037b3fb25e69c3a   

          make    model                                            version  \
49990   SUBARU  Outback                    SUBARU Outback 2.5i Limited 5p.   
49991  PORSCHE      911                 PORSCHE 911 Turbo Coupe A.M.08 2p.   
49992     JEEP  Compass          JEEP Compass 1.4 Mair 103kW Sport 4x2 5p.   
49993     SEAT     León  SEAT Leon ST 1.8 TSI 132kW 180CV StSp FR Plus 5p.   
49994     SEAT     León  SEAT Leon ST 1.6 TDI 85kW 115CV StSp Style Ed 5p.   
49995  HYUNDAI      i30        HYUNDAI i30 1.4 TGDI Tecno Fastback DCT 5p.   
49996  RENAULT   Laguna  RENAULT Laguna Coupe Limited 2.0 Energy dCi 15...   
49997  PEUGEOT      108           PEUGEOT 108 TOP Allure VTi 52kW 72CV 5p.   
49998     AUDI      RS4           AUDI RS4 Avant 4.2 FSI 450cv quattro 5p.   
49999  CITROEN       C2                    CITROEN C2 1.4 HDI VTR Plus 3p.   

       price  price_financed      fuel    year     kms  ...  doors  \
49990   9800             NaN  Gasolina  2012.0  118000  ...      5   
49991  67900             NaN  Gasolina  2008.0   99000  ...      2   
49992  21900             NaN  Gasolina  2020.0    5000  ...      5   
49993  19490         18490.0  Gasolina  2017.0   67900  ...      5   
49994  18590         16590.0    Diésel  2019.0   21153  ...      5   
49995  18490         16490.0  Gasolina  2018.0   47000  ...      5   
49996  14500         13551.0    Diésel  2015.0   68750  ...      2   
49997  11000          9000.0  Gasolina  2019.0   21422  ...      5   
49998  47900             NaN  Gasolina  2013.0   47900  ...      5   
49999   2790             NaN    Diésel  2006.0  106000  ...      3   

            shift                           color photos  is_professional  \
49990  Automático                    Gris / Plata      6            False   
49991  Automático                            Rojo     54             True   
49992      Manual                    Gris / Plata     29             True   
49993      Manual                          Blanco     34             True   
49994      Manual                    Gris / Plata     20             True   
49995  Automático                    Gris / Plata     26             True   
49996      Manual  KNG Gris Casiopea (metalizado)     30             True   
49997      Manual                    Gris / Plata     17             True   
49998  Automático        Gris / Plata (Antracita)     20             True   
49999      Manual                           Negro     21             True   

                                 dealer   province country  \
49990  6e55c8f1af9646ada8d52ca37d627d42   Tenerife   Spain   
49991                      Quality Cars   Valencia   Spain   
49992                           AJ CARS    Navarra   Spain   
49993                Flexicar Barcelona  Barcelona   Spain   
49994       Das Weltauto Gil Automocion     Madrid   Spain   
49995                   Flexicar Málaga     Málaga   Spain   
49996                      Ocasion Plus     Málaga   Spain   
49997                 Psa Retail Huelva     Huelva   Spain   
49998                    Codigocar Lugo       Lugo   Spain   
49999                   AUTOVALENCIA 19  Barcelona   Spain   

              publish_date 

In [ ]:
print("10 filas al azar:")
data.sample(n = 10)

10 filas al azar:


url                           company  \
45581  35e18158687c57b95a55fe1ac0e0fc59  9881bcdd5a0ad4733037b3fb25e69c3a   
46811  2b5e0cac5ac02f0f876906d342551fb5  9881bcdd5a0ad4733037b3fb25e69c3a   
22415  4b589062201ac2b0d197ca51a48b357c  9881bcdd5a0ad4733037b3fb25e69c3a   
38216  9c4d0c8591578a41424de910458994c4  9881bcdd5a0ad4733037b3fb25e69c3a   
19780  ef1217e1ee4218863eb88523896cd2cc  9881bcdd5a0ad4733037b3fb25e69c3a   
42519  d5b1e69b0ba7be89bcdf1791faa5f4be  9881bcdd5a0ad4733037b3fb25e69c3a   
40427  876c2b7337c726cda2bd5cd5a7d07a3a  9881bcdd5a0ad4733037b3fb25e69c3a   
25442  34102e22ef874cee6d968aaf5c7df9ba  9881bcdd5a0ad4733037b3fb25e69c3a   
48490  cfb58945f00002968ac9e07f4706d0cd  9881bcdd5a0ad4733037b3fb25e69c3a   
4711   af0955916687e1f89237be49ae2aa7b4  9881bcdd5a0ad4733037b3fb25e69c3a   

                make        model  \
45581           SEAT        Ateca   
46811           FORD        Focus   
22415         TOYOTA         Rav4   
38216         NISSAN      QASHQAI   
19780           OPEL     Insignia   
42519  MERCEDES-BENZ      Clase A   
40427     VOLKSWAGEN         Golf   
25442           FORD  Grand C-Max   
48490           FORD     EcoSport   
4711         CITROEN           C4   

                                                 version  price  \
45581  SEAT Ateca 2.0 TDI 140kW 190CV DSG 4Dr StSp Xc...  22500   
46811                       FORD Focus 1.8 TDCi Ghia 5p.   3990   
22415                  TOYOTA Rav4 150D 4x2 Yokubari 5p.  14500   
38216        NISSAN QASHQAI DIGT 85 kW 115 CV ACENTA 5p.  16350   
19780  OPEL Insignia ST 2.0 CDTi SS TURBO D Excellenc...  29990   
42519            MERCEDES-BENZ Clase A A 180 d Urban 5p.  17900   
40427              VOLKSWAGEN Golf 2.0 TSI 210cv GTI 3p.  14000   
25442  FORD Grand CMax 2.0 TDCi 110kW Business PowerS...  14890   
48490  FORD EcoSport 1.0T EcoBoost 92kW 125CV SS ST L...  17990   
4711                                             CITROEN   2900   

       price_financed      fuel    year     kms  ...  doors       shift  \
45581         20500.0    Diésel  2017.0  135000  ...      5  Automático   
46811             NaN    Diésel  2006.0  225000  ...      5      Manual   
22415             NaN    Diésel  2012.0   77438  ...      5      Manual   
38216         14715.0  Gasolina  2018.0   29000  ...      5      Manual   
19780         26900.0    Diésel  2017.0    2055  ...      5      Manual   
42519         16900.0    Diésel  2016.0   38000  ...      5      Manual   
40427             NaN  Gasolina  2010.0  180000  ...      3      Manual   
25442         14890.0    Diésel  2017.0   77000  ...      5  Automático   
48490         16490.0  Gasolina  2020.0       0  ...      5      Manual   
4711              NaN    Diésel  2005.0  258000  ...      5      Manual   

                           color photos  is_professional  \
45581                       Rojo      2             True   
46811                       Azul     17             True   
22415                       Azul     11            False   
38216       326 Blanco (sólido)     48             True   
19780  Gris / Plata (GRIS ACERO)     13             True   
42519                     Blanco      9             True   
40427               Gris / Plata     11            False   
25442                      Negro     29             True   
48490               Gris / Plata     15             True   
4711                       Negro      7            False   

                                 dealer    province country  \
45581                Multiautos Ourense      Orense   Spain   
46811                       Dcars Spain      Málaga   Spain   
22415  ffc150a160d37e92012c196b6af4160d   Barcelona   Spain   
38216                         AUTO BACK      Madrid   Spain   
19780                       Opel Zavisa    Zaragoza   Spain   
42519                       4DRIVE Cars   Barcelona   Spain   
40427  262031397020fd8df478ec13b4b096c5  Pontevedra   Spain   
25442              AUTOCONFI - IDILICAR      Madrid

### **Ejercicio 7**
Escribir un programa que a partir del dataframe definido en el **ejercicio 6**, nos muestre el tamaño del dataframe, el tipo de datos que contiene y su uso en memoria, y un breve resumen de los datos contenidos en cada columna.

In [ ]:
# Ejercicio 7
print("Tamaño del dataframe", data.size)

Tamaño del dataframe 1050000


In [ ]:
print("Tipo de datos por columna y uso en memoria")
data.info()

Tipo de datos por columna y uso en memoria
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 21 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   url              50000 non-null  object 
 1   company          50000 non-null  object 
 2   make             49998 non-null  object 
 3   model            49995 non-null  object 
 4   version          50000 non-null  object 
 5   price            50000 non-null  int64  
 6   price_financed   23563 non-null  float64
 7   fuel             49954 non-null  object 
 8   year             49998 non-null  float64
 9   kms              50000 non-null  int64  
 10  power            41472 non-null  float64
 11  doors            50000 non-null  int64  
 12  shift            49889 non-null  object 
 13  color            49406 non-null  object 
 14  photos           50000 non-null  int64  
 15  is_professional  50000 non-null  bool   
 16  dealer         

In [ ]:
print("Resumen")
data.describe()

Resumen


price  price_financed          year           kms  \
count   50000.000000    23563.000000  49998.000000  5.000000e+04   
mean    15166.270260    18480.029283   2012.311032  1.163591e+05   
std     16485.669747    13389.800738      6.677760  1.072921e+05   
min       300.000000      700.000000   1970.000000  0.000000e+00   
25%      5500.000000    10790.000000   2007.000000  3.830000e+04   
50%     11750.000000    15500.000000   2015.000000  9.999900e+04   
75%     19800.000000    21995.000000   2018.000000  1.749000e+05   
max    549900.000000   428999.000000   2021.000000  5.000000e+06   

              power         doors        photos  
count  41472.000000  50000.000000  50000.000000  
mean     146.396388      4.505380     16.199120  
std       71.283964      0.868001     12.422882  
min       29.000000      2.000000      0.000000  
25%      109.000000      4.000000      7.000000  
50%      130.000000      5.000000     13.000000  
75%      163.000000      5.000000     23.000000  
max      800.000000      5.000000     54.000000

### **Ejercicio 8**
Escribir un programa que a partir del dataframe definido en el **ejercicio 6** nos muestre los coches que se encuentran por debajo de 5000 euros de la marca Volkswagen

In [ ]:
# Ejercicio 8
data[(data["price"] < 5000) & (data["make"] == "VOLKSWAGEN")]

url                           company  \
11     8dadc0a13657e83e90a972e74456f701  9881bcdd5a0ad4733037b3fb25e69c3a   
12     254023385c971f3854bbbb2f65b475e8  9881bcdd5a0ad4733037b3fb25e69c3a   
23     ad1cd419582b0ee1617498592ba55dd8  9881bcdd5a0ad4733037b3fb25e69c3a   
65     b21b779ae2ffa8cbdebf75ef0e12a9ef  9881bcdd5a0ad4733037b3fb25e69c3a   
83     f240ef4476f35b23a9390693f4c5fd97  9881bcdd5a0ad4733037b3fb25e69c3a   
...                                 ...                               ...   
49708  68115c3c64779a65527cdae21b36313f  9881bcdd5a0ad4733037b3fb25e69c3a   
49752  555c66ec619b4ca865aaf8b712c60d84  9881bcdd5a0ad4733037b3fb25e69c3a   
49875  cb9851d79ee91aaed7895dd7cb194a6f  9881bcdd5a0ad4733037b3fb25e69c3a   
49908  5408fcd9a37144f6d23d3c8370f4a6f9  9881bcdd5a0ad4733037b3fb25e69c3a   
49965  c8b8e7ec796d945f0446c8d26c122ecf  9881bcdd5a0ad4733037b3fb25e69c3a   

             make        model                                      version  \
11     VOLKSWAGEN         Golf                         VOLKSWAGEN Golf  3p.   
12     VOLKSWAGEN         Polo        VOLKSWAGEN Polo 75 Trendline Auto 3p.   
23     VOLKSWAGEN      Phaeton                      VOLKSWAGEN Phaeton  5p.   
65     VOLKSWAGEN         Golf                         VOLKSWAGEN Golf  5p.   
83     VOLKSWAGEN       Passat  VOLKSWAGEN Passat 2.0 TDI 140cv Advance 4p.   
...           ...          ...                                          ...   
49708  VOLKSWAGEN       Passat                       VOLKSWAGEN Passat  4p.   
49752  VOLKSWAGEN  Transporter                  VOLKSWAGEN Transporter  5p.   
49875  VOLKSWAGEN       Passat  VOLKSWAGEN Passat 2.0 TDI 140cv Advance 4p.   
49908  VOLKSWAGEN         Golf                         VOLKSWAGEN Golf  2p.   
49965  VOLKSWAGEN         Polo                                   VOLKSWAGEN   

       price  price_financed      fuel    year     kms  ...  doors  \
11      1700             NaN    Diésel  1990.0  350000  ...      3   
12      1300             NaN  Gasolina  2001.0  217000  ...      3   
23      3750             NaN    Diésel  2006.0     400  ...      5   
65      4800             NaN    Diésel  2007.0  213000  ...      5   
83      3400             NaN    Diésel  2006.0  272000  ...      4   
...      ...             ...       ...     ...     ...  ...    ...   
49708   3500             NaN  Gasolina  2007.0  300100  ...      4   
49752   1950             NaN    Diésel  1994.0  500000  ...      5   
49875   4990          4990.0    Diésel  2006.0  165000  ...      4   
49908    800             NaN  Gasolina  1994.0  200000  ...      2   
49965   1600             NaN  Gasolina  2005.0  199700  ...      3   

            shift         color photos  is_professional  \
11         Manual          Rojo      4            False   
12         Manual          Azul      1            False   
23     Automático         Verde      9            False   
65         Manual         Negro      7            False   
83         Manual  Gris / Plata      9             True   
...           ...           ...    ...              ...   
49708      Manual           NaN      9            False   
49752      Manual        Blanco      9            False   
49875      Manual  Gris / Plata      1             True   
49908      Manual          Azul      5            False   
49965      Manual  Gris / Plata      0            False   

                                 dealer   province country  \
11     a425a46b14a78f533e40e974b3d31385  Guipúzcoa   Spain   
12     a96e8f71351fbe70573b70189c0dd2bb  Barcelona   Spain   
23     647431b5ca55b04fdf3c2fce31ef1915     Madrid   Spain   
65     a94652aa97c7211ba8954dd15a3cf838    Almería   Spain   
83                                 RAUL     Madrid   Spain   
...                                 ...        ...     ...   
49708  ab02fceb9689114b1cd1844e456c0695    Vizcaya   Spain   
49752  a208a1dbed72a7c5f6b0c8c660c75766   Alicante   Spain   
49875                          Dv Motor     Málaga   S

### **Ejercicio 9**
Escribir un programa que a partir del dataframe definido en el **ejercicio 6** nos muestre los 10 coches más nuevos que sean híbridos enchufables y cuesten menos de 10000 euros.

In [ ]:
# Ejercicio 9
data[data["fuel"] == "Híbrido"].sort_values(by="price", ascending=True).head(n=10)

url                           company  \
24915  15f816e6442a7d8a603c39251f27d1a3  9881bcdd5a0ad4733037b3fb25e69c3a   
49169  e99467c276245fd7506bd6226d41a7ad  9881bcdd5a0ad4733037b3fb25e69c3a   
32735  2297c13b7120c6d837e9835fbc90c765  9881bcdd5a0ad4733037b3fb25e69c3a   
16846  483ed09338e13c7c556c43e99e348499  9881bcdd5a0ad4733037b3fb25e69c3a   
6318   9001fad6719aa2c1199a923b4db064e8  9881bcdd5a0ad4733037b3fb25e69c3a   
31960  cadd7fe1048aa13e23d2fc4cfdb84ae1  9881bcdd5a0ad4733037b3fb25e69c3a   
37066  708e40093808e1b56952a34f5fd843d8  9881bcdd5a0ad4733037b3fb25e69c3a   
8534   f2f579140f9a5a57daa0a4edd26487c9  9881bcdd5a0ad4733037b3fb25e69c3a   
16808  f025283e52565169032772e647c73a47  9881bcdd5a0ad4733037b3fb25e69c3a   
18242  85c91a30b8139709fa81ec727fb0f980  9881bcdd5a0ad4733037b3fb25e69c3a   

         make    model                                    version  price  \
24915  TOYOTA    Prius          TOYOTA Prius 1.5 VVTi SOL HSD 5p.   4200   
49169  TOYOTA    Prius              TOYOTA Prius 1.5 VVTi HSD 5p.   4499   
32735   HONDA  Insight  HONDA Insight 1.3 iVTEC IMA Executive 5p.   4500   
16846   HONDA     CR-Z          HONDA CRZ 1.5 iVTEC IMA Sport 3p.   5499   
6318    HONDA    Civic        HONDA Civic 1.3 iDSi IMA Hybrid 4p.   5500   
31960  TOYOTA    Prius           TOYOTA Prius 1.8 HSD ADVANCE 5p.   5500   
37066  TOYOTA    Prius           TOYOTA Prius 1.8 HSD ADVANCE 5p.   5900   
8534   TOYOTA    Prius          TOYOTA Prius 1.5 VVTi SOL HSD 5p.   5999   
16808   HONDA     CR-Z            HONDA CR-Z 1.5 iVTEC IMA GT 3p.   6000   
18242  TOYOTA    Prius          TOYOTA Prius 1.5 VVTi SOL HSD 5p.   6200   

       price_financed     fuel    year     kms  ...  doors       shift  \
24915             NaN  Híbrido  2009.0  431000  ...      5  Automático   
49169             NaN  Híbrido  2007.0  178000  ...      5  Automático   
32735             NaN  Híbrido  2011.0  205000  ...      5  Automático   
16846             NaN  Híbrido  2011.0  197000  ...      3      Manual   
6318           5500.0  Híbrido  2007.0  127500  ...      4  Automático   
31960             NaN  Híbrido  2009.0  219000  ...      5  Automático   
37066             NaN  Híbrido  2010.0  247000  ...      5  Automático   
8534              NaN  Híbrido  2009.0  180335  ...      5  Automático   
16808             NaN  Híbrido  2011.0  110000  ...      3      Manual   
18242             NaN  Híbrido  2008.0  178000  ...      5  Automático   

                           color photos  is_professional  \
24915               Gris / Plata     19             True   
49169                      Negro     23             True   
32735               Gris / Plata     12            False   
16846                     Blanco     11             True   
6318         Gris / Plata (gris)      4             True   
31960                      Negro     10            False   
37066                       Azul     18             True   
8534                Gris / Plata     13             True   
16808                       Azul     10            False   
18242  Gris / Plata (GRIS PLOMO)     17             True   

                                 dealer    province country  \
24915             Impo Expo By 5210 S.L      Málaga   Spain   
49169                           M7-Cars     Vizcaya   Spain   
32735  036e3491ba499df64611c82b6bcdd37d      Girona   Spain   
16846                         Roberauto      Madrid   Spain   
6318                     Antigua Motors  Las Palmas   Spain   
31960  e3eb29693b548564f8760fc5353736a4      Madrid   Spain   
37066                 D & D Automóviles    A Coruña   Spain   
8534            Mas Kilometros 69, S.L.    Zaragoza   Spain   
16808  c09e2995b865f51e83783a068a9eb8ea      Madrid   Spain   
18242                               SMC      Madrid   Spain   

              publish_date          insert_date  
24915  2020-12-16 22:59:50  2021-01-15 00:00:00  
49169  2020-12-22 01:33:02  2021-01-15 00:00:00  
32735  2020-10-24 23:57:47  202

## **Ejercicio 10**
Escribir un programa que a partir del dataframe definido en el **ejercicio 6** nos calcule una nueva columna con el ahorro porcentual con respecto al precio base de financiar el coche.

In [ ]:
# Ejercicio 10
data["savings"] = (data["price"] - data["price_financed"])/data["price"] * 100

In [ ]:
data.sort_values(by="savings", ascending=False).head(10)

url                           company  \
40732  744475da4d021cd481cf2dcc30ca9c16  9881bcdd5a0ad4733037b3fb25e69c3a   
49118  30938910a5d3242214ab3addc0421cf9  9881bcdd5a0ad4733037b3fb25e69c3a   
10264  4540a074f85e6f3ac963e5c0d4787bc9  9881bcdd5a0ad4733037b3fb25e69c3a   
28246  8d830d6b52a9a3dc4683b1c7b1775dda  9881bcdd5a0ad4733037b3fb25e69c3a   
46994  5aab27edd4a86621f0c5896a2b543159  9881bcdd5a0ad4733037b3fb25e69c3a   
5659   75089cde3b8f3aacad6746c213cd4e88  9881bcdd5a0ad4733037b3fb25e69c3a   
47381  8a977f80434300e8c0bc235e93cb8f50  9881bcdd5a0ad4733037b3fb25e69c3a   
1045   e6a382f3f6f6532ecb0e671089499edb  9881bcdd5a0ad4733037b3fb25e69c3a   
15341  2ec09b7ee027e426a9745296ec2706e4  9881bcdd5a0ad4733037b3fb25e69c3a   
7951   49f5e24e551160c667316d0a07773283  9881bcdd5a0ad4733037b3fb25e69c3a   

          make   model                                           version  \
40732  CITROEN  C-Zero                       CITROEN CZero Seduction 5p.   
49118   NISSAN   Micra      NISSAN Micra IGT 74 kW 100 CV E6D Acenta 5p.   
10264   NISSAN   Micra      NISSAN Micra IGT 74 kW 100 CV E6D Acenta 5p.   
28246  PEUGEOT     208         PEUGEOT 208 5P STYLE 1.2L PureTech 82 5p.   
46994   ABARTH    500C  ABARTH 500C 1.4 16v TJet 595 107kW 145CV E6D 2p.   
5659       NaN     D2S                                      D2S 27kW 3p.   
47381      NaN     D2S                                      D2S 27kW 3p.   
1045   PEUGEOT     108              PEUGEOT 108 Allure VTi 52kW 72CV 5p.   
15341     FIAT     500           FIAT 500 1.2 8v 69 CV Color Therapy 3p.   
7951      FIAT     500           FIAT 500 1.2 8v 69 CV Color Therapy 3p.   

       price  price_financed       fuel    year    kms  ...       shift  \
40732  22500         12900.0  Eléctrico  2020.0     10  ...  Automático   
49118  18275         11200.0   Gasolina  2020.0      0  ...      Manual   
10264  18275         11200.0   Gasolina  2020.0      0  ...      Manual   
28246   9900          6400.0   Gasolina  2016.0  71092  ...      Manual   
46994  26410         17400.0   Gasolina  2020.0      0  ...      Manual   
5659   21495         14495.0  Eléctrico  2021.0      3  ...  Automático   
47381  21495         14495.0  Eléctrico  2021.0      6  ...  Automático   
1045   11500          8000.0   Gasolina  2018.0  12301  ...      Manual   
15341   9999          6999.0   Gasolina  2014.0  43878  ...      Manual   
7951    9999          6999.0   Gasolina  2014.0  43878  ...      Manual   

              color photos is_professional  \
40732  Gris / Plata     22            True   
49118         Beige     11            True   
10264         Beige     12            True   
28246          Rojo     11            True   
46994        Blanco     15            True   
5659          Beige     16            True   
47381          Azul     15            True   
1045   Gris / Plata     18            True   
15341          Rojo     29            True   
7951           Rojo     29            True   

                                         dealer  province country  \
40732                         Garaje Las Flores  Albacete   Spain   
49118                            NISSAN ALMENAR  Valencia   Spain   
10264                            NISSAN ALMENAR  Alicante   Spain   
28246         PSA Retail Valencia - Tres Cruces  Valencia   Spain   
46994                                  Motordos   Granada   Spain   
5659                              GJ AUTOMOTIVE    Burgos   Spain   
47381                             GJ AUTOMOTIVE    Burgos   Spain   
1045          PSA Retail Valencia - Tres Cruces  Valencia   Spain   
15341                          Antón Automoción   Vizcaya   Spain   
7951   Concesión Oficial Citroën Álava Lascaray     Álava   Spain   

              publish_date          insert_date    savings  
40732  2020-12-28 23:27:21  2021-01-15 00:00:00  42.666667  
49118  2020-12-27 14:13:42  2021-01-15 00:00:00  38.714090  
10264  2020-12-23 13:05:04  2021-01-15 00:00:00  38.714090  
28246  2020-12